title: Jonny Muir Site
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 20
paginate_path: "blog/page:num"
encoding: utf-8

kramdown:
  syntax_highlighter: coderay

plugins: [jekyll-paginate]

exclude:
  - Gemfile
  - Gemfile.lock

include:
  - .well-known/*

collections:
  lessons:
    output: true
